# ====== CƠ BẢN ======
set -g mouse on
set -g default-terminal "tmux-256color"
set-window-option -g mode-keys vi

# Prefix
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Split shortcuts
unbind %
bind | split-window -h
unbind '"'
bind - split-window -v

# Reload config
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Resize panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z

# Navigate panes (works with vim)
bind-key C-h if-shell "[[ $(tmux display -p '#{pane_in_mode}') -eq 1 ]]" "send-keys C-h" "select-pane -L"
bind-key C-j if-shell "[[ $(tmux display -p '#{pane_in_mode}') -eq 1 ]]" "send-keys C-j" "select-pane -D"
bind-key C-k if-shell "[[ $(tmux display -p '#{pane_in_mode}') -eq 1 ]]" "send-keys C-k" "select-pane -U"
bind-key C-l if-shell "[[ $(tmux display -p '#{pane_in_mode}') -eq 1 ]]" "send-keys C-l" "select-pane -R"

# Copy mode
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane


# Hooks
set-hook -g client-prefix 'display-popup -E -w 30% -h 20% "echo PREFIX MODE; sleep 0.5"'


# ====== THEME: CATPPUCCIN ======
set -g @catppuccin_flavor "mocha"  # latte, frappe, macchiato, mocha
set -g @catppuccin_window_status_style "rounded"  # basic, rounded, slanted, none

# ====== PLUGINS ======
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux' 
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# ====== THEME STATUS BAR ======
set -g status-right-length 100
set -g status-left-length 101
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# ====== CONTINUUM / RESURRECT ======
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

set -g @continuum-save-interval '10'

# Pls rememember to clone the TPM from github:
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# ====== TPM INIT ======
run '~/.tmux/plugins/tpm/tpm'
